[theme]

# Primary accent for interactive elements
primaryColor = '#535353'

# Background color for the main content area
backgroundColor = '#1a2333'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#313945'

# Color used for almost all text
textColor = '#ebeef2'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"